### ISSUE TITLE
Small and big things about channelTube

### ISSUE THREAD

**Issue by PaulEins** [TheWicklowWolf/ChannelTube#13]
Hi TheWicklowWolf, I'm totally celebrating your tool. I found it on [Mariu's site](https://mariushosting.com/how-to-install-channeltube-on-your-synology-nas/) and it's already helping me a lot.

I decided to use Plex after all, which I have running together with ChannelTube in Docker on my Synology.
Now I haven't found any other way to reach you, so I want to write my thoughts here. 

1. How can I add all my YouTube subscriptions to your tool at once? By hand you have to enter each page individually. 
Is it not possible to mark the whole page here and then copy it into your tool? You can also officially download only the subscriptions from Google. They also arrive immediately via e-mail.
https://docs.invidious.io/export-youtube-subscriptions/
<img width="1468" alt="Bildschirmfoto 2024-10-08 um 20 42 28" src="https://github.com/user-attachments/assets/035a100a-99b1-411f-bd90-e36bc371dd96">
<img width="985" alt="Bildschirmfoto 2024-10-08 um 20 45 24" src="https://github.com/user-attachments/assets/8d934529-e9e0-428d-8c28-3744a4c472c7">
<img width="1463" alt="Bildschirmfoto 2024-10-08 um 20 51 44" src="https://github.com/user-attachments/assets/b329bc32-2ba8-4e0f-9c41-b255f2cc3647">

2. Can you integrate SponsorBlock? So that the videos are cut off? Could you possibly activate the options for this? https://sponsor.ajay.app/ or https://chromewebstore.google.com/detail/sponsorblock-f%C3%BCr-youtube/mnjggcdmjocbbbhaepdhchncahnbgone

3. Can you also save the text from the video description in the video file? Maybe even Plex does that. I don't know where the information comes from.  can you add the image from YouTube to the video? Sometimes there is a lot, sometimes only the file is raw. 
<img width="1147" alt="Bildschirmfoto 2024-10-08 um 20 34 50" src="https://github.com/user-attachments/assets/146f9161-9a71-427f-a8ba-bbce902dc4e7">
<img width="1469" alt="Bildschirmfoto 2024-10-08 um 20 35 22" src="https://github.com/user-attachments/assets/83309edf-e3e2-4ea7-aefa-b92e7b8f7099">

4. can you also do this for [Twitch Live Stream](https://www.twitch.tv/)? There is already the website [streamrecorder.io](https://streamrecorder.io) where you can store 3 streamers that you can then download. If you could automate this, then you would also have the Twitch videos on your box. And with Streamrecorder the advertising bug is already recognized and removed. 
<img width="1466" alt="Bildschirmfoto 2024-10-08 um 20 13 27" src="https://github.com/user-attachments/assets/3234666c-0fbe-4b10-933a-79e549848a4b">

6. Thanks again. Thanks again. Your tool is already great. =)

**Comment by TheWicklowWolf** [comment]
Hi @PaulEins,

Firstly, it's wild to see someone write a blog post about this..

Let me address your points:

1. **Adding YouTube subscriptions in bulk**: I currently have no plans to add this as a feature. It's relatively simple to do in the UI (or alternatively by editing the `channel_list.json` file in the config folder), and I don't consider it a critical feature.

2. **SponsorBlock integration**: This feature is already implemented, see here:  
   https://github.com/TheWicklowWolf/ChannelTube/blob/db51d811e603271c6171b493719dd352a5906be5/src/ChannelTube.py#L365-L368

3. **Thumbnails and metadata**: These are already embedded in the video files:  
   https://github.com/TheWicklowWolf/ChannelTube/blob/db51d811e603271c6171b493719dd352a5906be5/src/ChannelTube.py#L387-L390

   For Plex, you'll just need to adjust your scanner/metadata configuration. The main objective is to set it to "Prefer local metadata" to make full use of this.

4. **Twitch Live Stream support**: Since this tool is primarily aimed at YouTube, adding Twitch support isn't something I have any plans for. In theory, it could work if `yt-dlp` supports it, but I'm unsure about how the info is parsed and haven't tested for Twitch-specific streams.

Best of luck with it.

**Comment by PaulEins** [comment]
Can you set a single button for a single channel check? When there is a new video and the channel is at the very end of the list, it takes a long time. Because everything has to be checked first.

**Comment by TheWicklowWolf** [comment]
> Can you set a single button for a single channel check? When there is a new video and the channel is at the very end of the list, it takes a long time. Because everything has to be checked first.

The goal is to keep the UI as minimal as possible and have everything running automatically. The manual sync start is intended only for occasional uses. While adding a single-channel check isn’t a major change, there are currently no plans to implement that feature.

As a workaround, you can adjust the `Search Limit` to a value that suits your needs, which should help speed up the process.
